---
grails:
  profile: web
  codegen:
    defaultPackage: simpleappwithsecurity
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
  groovy:
    template:
      check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html: 
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal: 
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    hibernate:
        cache:
            queries: false
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

hibernate:
    cache:
        use_second_level_cache: false
        use_query_cache: false

---
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            adapter: mysql2
            database: smart_irrigation
            encoding: utf8
            host : smart-irrigation.canqqif3vrwd.us-west-1.rds.amazonaws.com
            username: smart_irrigation
            password: eWGGGog8BD08KAoj
            reconnect: true
            port: 3306
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            adapter: mysql2
            database: smart_irrigation
            encoding: utf8
            host : smart-irrigation.canqqif3vrwd.us-west-1.rds.amazonaws.com
            username: smart_irrigation
            password: eWGGGog8BD08KAoj
            reconnect: true
            port: 3306
